name: CombatEventsLoot
main: net.milkbowl.combatevents.loot.CombatEventsLoot
version: 1.0-b000
author: Sleaker
depend: [Vault, CombatEventsCore]
description: >
             A plugin that allows the changing of loot drops.